# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrowjobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='asp',
            old_name='desciption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='asp',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrowjobs.Contact'),
        ),
    ]
