# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-25 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrowjobs', '0002_auto_20160718_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asp',
            name='contact',
        ),
        migrations.AddField(
            model_name='asp',
            name='contact',
            field=models.ManyToManyField(to='arrowjobs.Contact'),
        ),
    ]
