# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-25 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrowjobs', '0003_auto_20160725_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='__@__.__', max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='333222111', max_length=20),
        ),
    ]
