# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrowjobs', '0004_auto_20160725_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='asp',
            name='asp_design',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
