# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-25 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrowjobs', '0005_asp_asp_design'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asp',
            name='aspnum',
        ),
        migrations.AddField(
            model_name='asp',
            name='design_id',
            field=models.CharField(default=3434, max_length=20),
            preserve_default=False,
        ),
    ]
