# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrowjobs', '0007_auto_20160825_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asp',
            name='datein',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
