# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrowjobs', '0008_auto_20160901_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asp',
            old_name='datein',
            new_name='date_in',
        ),
    ]
